"""agregar columna eliminado a libros

Revision ID: 8f2065c646e7
Revises: ebd2b6e05186
Create Date: 2026-09-28 22:17:42.008612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2065c646e7'
down_revision = 'ebd2b6e05186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejemplares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('codigo_inventario', sa.VARCHAR(length=100), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'PRESTADO', 'NO_DISPONIBLE', name='estadoejemplar'), nullable=True),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_prestamo', sa.Date(), nullable=False),
    sa.Column('fecha_devolucion', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros', schema=None) as batch_op:
        batch_op.drop_column('eliminado')

    op.drop_table('prestamos')
    op.drop_table('ejemplares')
    # ### end Alembic commands ###
