"""creacion de tabla libro escritores

Revision ID: ebd2b6e05186
Revises: 5ee98f5178c6
Create Date: 2026-09-23 23:00:45.574404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd2b6e05186'
down_revision = '5ee98f5178c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros_categorias',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'categoria_id')
    )
    op.create_table('libros_escritores',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('escritor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escritor_id'], ['escritores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'escritor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros_escritores')
    op.drop_table('libros_categorias')
    # ### end Alembic commands ###
