--eN DB RELACIONALES EXISTE 3 TIPOS DE RELACIONES ENTRA TAVLAS
-- 1 - 1
-- ES UNA RELACION DE 2 TABLAS TENDRAN UN REGISTRO QUE REPRESENTE A LA OTRA EN UN SOLO REGISTRO 
--EJEMPLOS: USUARIO TIENE UNA PERSONA 
--LA CLAVE FORANEA: ES LA REPRESENTACION DEL REGISTRO (PK) DE LA TAVBLA A HACIA LA TABLA B 
-- LA CLAVE FORANEA (FK) NO IMPORTA EN CUAL DE LAS 2 TABLAS VAYA 


-- 1 - N
--UNA PERSONA PUEDE TENR VARIAS DIRECCIONES
--LA FK VA EN LA TABLA VARIAS, LA LLAVE FORANIA IRIA EN LA TABAL DE DIRECCIONES
--REPRESENTA QUE ESE REGISTRO LE PERTENECE A UNA PERSONA DETERMINADA


-- N - N * UN ALUMNO TIENE VARIOS CURSOS, UN CURSO TIENE VARIOS ALUMNOS
-- AL TENER UNA RELACION DE MUCHOS A MUCHOS LA LLAVE FORANEA NO PUEDE EXISTIR EN ALGUNAS DE LAS TABLAS
-- POR ELLOS SE CREA UNA TABLA INTERMEDIA, PIVOTE, PUENTE EL CUAL IRA LAS FK DE LAS 2 TABLAS OSEA DE FK ALUMNOS Y FK ALUMNOS

CREATE DATABASE directorio;

CREATE TABLE usuarios (
	id SERIAL PRIMARY KEY,
	nombre TEXT,
	correo TEXT UNIQUE
);

CREATE TABLE direcciones (
	id SERIAL PRIMARY KEY,
	calle TEXT NOT NULL,
	numero TEXT,
	referencia TEXT,
	distrito TEXT,
	--ASI SE AGREGAR LA LLAVE FORANEA DE UNA RELACION DE UNO A MUCHOS
	usuario_id INT, --Esto es una columna corriente
	CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) --aqui se crea la realcion
);

--Para eliminar toda la tabla direcciones
DROP TABLE	direcciones 

SELECT * FROM direcciones d 

----------------------------------------
-- Muchos a muchos
CREATE TABLE alumnos(
	id SERIAL PRIMARY KEY,
	nombre TEXT
)

CREATE TABLE cursos(
	id SERIAL PRIMARY KEY,
	nombre TEXT
)

CREATE TABLE alumnos_cursos(
	alumno_id INT,
	curso_id INT,
	CONSTRAINT fk_alumno FOREIGN KEY (alumno_id) REFERENCES alumnos(id),
	CONSTRAINT fk_curso FOREIGN KEY (curso_id) REFERENCES cursos(id),
	-- AL SER UNA TABLA PIVOTE PUENTE
	PRIMARY KEY (alumno_id, curso_id)
	
)












